project_name: kdiag
env:
  - CGO_ENABLED=0
before:
  hooks:
    # We strongly recommend running tests to catch any regression before release.
    # Even though, this an optional step.
    - go test ./...
    # As part of the release doc files are included as a separate deliverable for
    # consumption by Packer.io. To include a separate docs.zip uncomment the following command.
    - make ci-release-docs
builds:
  # A separated build to run the packer-plugins-check only once for a linux_amd64 binary
  -
    id: packer-plugin-arm-image
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath #removes all file system paths from the compiled executable
    ldflags:
      - '-s -w -X {{ .ModulePath }}/version.Version={{.Version}} -X {{ .ModulePath }}/version.Commit={{.Commit}} -X {{ .ModulePath }}/version.VersionPrerelease= '
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    binary: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'
archives:
- format: zip
  files:
    - none*
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS'
  algorithm: sha256

release:
  # If you want to manually examine the release before its live, uncomment this line:
  # draft: true
  # As part of the release doc files are included as a separate deliverable for consumption by Packer.io.
  # To include a separate docs.zip uncomment the extra_files config and the docs.zip command hook above.
  extra_files:
  - glob: ./docs.zip

changelog:
  skip: true

dockers:
  - use_buildx: true
    image_templates:
    - 'ghcr.io/solo-io/kdiag:{{ .Version }}'
    dockerfile: Dockerfile
    goos: linux
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--build-arg=VERSION={{.Version}}"
    - "--build-arg=COMMIT={{.Commit}}"
    - "--platform=linux/amd64,linux/arm64"