project_name: kubectl-diag
env:
  - CGO_ENABLED=0
builds:
  # A separated build to run the packer-plugins-check only once for a linux_amd64 binary
  -
    id: kubectl-diag
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath #removes all file system paths from the compiled executable
    ldflags:
      - '-s -w -X {{ .ModulePath }}/pkg/version.Version={{.Version}} -X {{ .ModulePath }}/pkg/version.Commit={{.Commit}} -X {{ .ModulePath }}/pkg/version.VersionPrerelease= '
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    binary: '{{ .ProjectName }}'
  -
    id: manager
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath #removes all file system paths from the compiled executable
    ldflags:
      - '-s -w -X {{ .ModulePath }}/pkg/version.Version={{.Version}} -X {{ .ModulePath }}/pkg/version.Commit={{.Commit}} -X {{ .ModulePath }}/pkg/version.VersionPrerelease= '
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    binary: manager

archives:
- name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  builds:
  - kubectl-diag
  format: tar.gz
  files:
    - LICENSE
checksum:
  name_template: '{{ .ProjectName }}_{{ .Tag }}_SHA256SUMS'
  algorithm: sha256

changelog:
  skip: true

dockers:
  - use: buildx
    image_templates:
    - 'ghcr.io/solo-io/kdiag:{{ .Version }}-amd64'
    dockerfile: Dockerfile.release
    goos: linux
    goarch: amd64
    ids:
      - manager
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--build-arg=VERSION={{.Version}}"
    - "--build-arg=COMMIT={{.Commit}}"
    - "--platform=linux/amd64"
  - use: buildx
    image_templates:
    - 'ghcr.io/solo-io/kdiag:{{ .Version }}-arm64v8'
    dockerfile: Dockerfile.release
    goos: linux
    goarch: arm64
    ids:
      - manager
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--build-arg=VERSION={{.Version}}"
    - "--build-arg=COMMIT={{.Commit}}"
    - "--platform=linux/arm64/v8"
docker_manifests:
  # https://goreleaser.com/customization/docker_manifest/
  - name_template: 'ghcr.io/solo-io/kdiag:{{ .Version }}'
    image_templates:
      - 'ghcr.io/solo-io/kdiag:{{ .Version }}-amd64'
      - 'ghcr.io/solo-io/kdiag:{{ .Version }}-arm64v8'
