apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: diag
spec:
  version: {{ .TagName }}
  homepage: https://github.com/solo-io/kdiag
  platforms:
  - {{ addURIAndSha "https://github.com/solo-io/kdiag/releases/download/{{ .TagName }}/kubectl-diag_{{.TagName}}_darwin_amd64.tar.gz" .TagName }}
    bin: kubectl-diag
    files:
    - from: kubectl-diag
      to: kubectl-diag
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        os: darwin
        arch: amd64
  - {{ addURIAndSha "https://github.com/solo-io/kdiag/releases/download/{{ .TagName }}/kubectl-diag_{{.TagName}}_darwin_arm64.tar.gz" .TagName }}
    bin: kubectl-diag
    files:
    - from: kubectl-diag
      to: kubectl-diag
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        os: darwin
        arch: arm64
  - {{ addURIAndSha "https://github.com/solo-io/kdiag/releases/download/{{ .TagName }}/kubectl-diag_{{.TagName}}_linux_amd64.tar.gz" .TagName }}
    bin: kubectl-diag
    files:
    - from: kubectl-diag
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        os: linux
        arch: amd64
  - {{ addURIAndSha "https://github.com/solo-io/kdiag/releases/download/{{ .TagName }}/kubectl-diag_{{.TagName}}_windows_amd64.tar.gz" .TagName }}
    bin: kubectl-diag.exe
    files:
    - from: kubectl-diag.exe
      to: kubectl-diag.exe
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        os: windows
        arch: amd64
  shortDescription: Diagnostics tools for kubernetes developers.
  caveats: |
    This uses high privilege ephemeral containers, and not suited for production.
  description: |
    When working with systems that span multiple micro-services, it can be hard to get a local setup
    working in-order to debug it. This plugin has a set of tools to assist you with that. Redirecting traffic
    from a pod to your laptop, so you can only run the components you care about locally. Viewing logs
    from multiple pods at the same time, so you can see how the system responds on both ends.
