FROM --platform=${TARGETPLATFORM} ghcr.io/solo-io/kdiag-shell:8ef4ab43
COPY manager /usr/local/bin/manager

WORKDIR /

# Install dependencies
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    iproute2 iptables nftables \
    strace make \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/usr/local/bin/manager"]
