name: goreleaser

on:
  pull_request:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.12.0"
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.9.1'
      - name: Pre checks
        run: |
          ./ci/precheck.sh
      - name: Tests
        run: |
          ./ci/do_ci.sh
